### PR TITLE
Update blender_simplify to Blender 2.8 API

### PR DESCRIPTION
**Pull request by wlcosta**
Using the current code on Blender 2.8 yields the following error:

```
bpy.data.objects['Camera'].select = True
AttributeError: 'Object' object has no attribute 'select'
```

According to [API changes](https://wiki.blender.org/wiki/Reference/Release_Notes/2.80/Python_API/Scene_and_Object_API) in Blender 2.8:

_In 2.7x, you could directly (de)select an Object from its select property. This has been removed in 2.8x, in favor of some get/set functions._

Therefore, we need to change this piece of code to allow for direct usage on Blender 2.8, which is now the default for installation.

### CODE REVIEW

**Comment by ajhamdi** [comment]
@wlcosta So what is the suggested adjustments to work on Blender 2.8 ?
